karpenter:
  serviceAccount:
    create: false
  nodeSelector:
    kubernetes.io/os: linux
    nodeType: admin
  settings:
    aws:
      clusterName:
      clusterEndpoint:
      defaultInstanceProfile:
      interruptionQueueName:
