cost-analyzer:
  global:
    grafana:
      enabled: false
      proxy: false
    prometheus:
      enabled: false
      fqdn: http://grafana-stack-kube-prometh-prometheus:9090

  imageVersion: prod-1.103.3
  kubecostFrontend:
    image: public.ecr.aws/kubecost/frontend

  kubecostModel:
    image: public.ecr.aws/kubecost/cost-model

  kubecostMetrics:
    emitPodAnnotations: true
    emitNamespaceAnnotations: true

  prometheus:
    server:
      image:
        repository: public.ecr.aws/kubecost/prometheus
        tag: v2.35.0
    serviceAccounts:
      nodeExporter:
        create: false

    kube-state-metrics:
      disabled: false

    nodeExporter:
      enabled: false
      tolerations:
        - operator: 'Exists'

    configmapReload:
      prometheus:
        enabled: false
        image:
          repository: public.ecr.aws/bitnami/configmap-reload
          tag: 0.7.1

  reporting:
    productAnalytics: false
